pip install google-cloud-speech
pip install google-cloud-storage
pip install moviepy
pip install Wave
pip install python-docx
pip install tinytag
pip install Flask
pip install Flask-Cors
pip install DateTime
pip install python-constraint
pip install pickle
pip install opencv-python
pip install lmdb
pip install numpy
pip install glob
pip install Flask
pip install Flask-Cors
pip install tensorflow
pip install argparse
pip install editdistance